-- INSERT INTO restrictions(id, restriction_name, createdAt, updatedAt)
-- VALUES(1, "Reservation", NOW(), NOW());
-- INSERT INTO restrictions(id, restriction_name, createdAt, updatedAt)
-- VALUES(1, "Owner Block", NOW(), NOW());